services:
  - type: web
    name: influencer-sponsorship-api
    env: python
    region: oregon
    plan: free
    pythonVersion: "3.11"
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: influencer-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: influencer-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: SECURITY_PASSWORD_SALT
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: https://influencer-sponsorship-vue-git-main-nithesh2303s-projects.vercel.app,https://influencer-sponsorship-gghaifvqt-nithesh2303s-projects.vercel.app

  - type: redis
    name: influencer-redis
    ipAllowList: []
    plan: starter

databases:
  - name: influencer-db
    databaseName: influencer_sponsorship
    plan: starter